blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/UNC-GDSC/Rust-URL-Shortening/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://github.com/UNC-GDSC/Rust-URL-Shortening/tree/main/docs
    about: Check the documentation for guides and references
